bin_folder: "../bin"
target_folder: "../target"

remote_folder: "/home/{{ ansible_user }}"

# Extra properties passed to the JVM.
java_opts: ""

# Properties which are mostly static during the permutation
num_threads: 100
num_keys: 100000
test_duration: 120
warmup_duration: 60
msg_size: 1000

# Properties defined by the permutation
use_virtual_threads: true
script_file: "perf-test-gcp.sh"
control_config: "control-gcp.xml"
cache_config: "dist-sync-gcp.xml"

# JDKs utilized for testing
jdks:
  - 21.0.2-open
  - 25.ea.5-open
  - 17-open
jdk_version: 21.0.2-open

# Extra variables
sdkman_folder: /home/{{ ansible_user }}/.sdkman
