# JDKs utilized for testing
jdks:
  - 21.0.2-open
  - 25.ea.32-open
  - 26.ea.7-open
jdk_version: 21.0.2-open

vthreads:
  - true

properties:
  - jgroups.bundler.type:
    - pd
    - tq
  - jgroups.bundler.use_single_sender_thread:
    - 'true'
    - 'false'
  - bundler.use_ringbuffer:
    - 'true'
    - 'false'

# States not allowed in the permutation.
forbidden_states: []
