# JDKs utilized for testing
jdks:
  - 21.0.2-open
  - 25.ea.31-open
  - 26.ea.6-open
jdk_version: 21.0.2-open

vthreads:
  - true

# States not allowed in the permutation.
forbidden_states:
  - jdk_version: 17.0.15-tem
    use_virtual_threads: true
