# JDKs utilized for testing
jdks:
  - 21.0.2-open
  - 24.0.2-open
  - 25.ea.34-open
jdk_version: 21.0.2-open

vthreads:
  - true

properties:
  - jgroups.bundler.type:
    - pd
    - tq
  - jgroups.bundler.use_single_sender_thread:
    - 'true'
    - 'false'
  - bundler.use_ringbuffer:
    - 'true'
    - 'false'

# States not allowed in the permutation.
forbidden_states:
  # Write the option as they are provided to the JVM.
  # It will perform a sub-set mathc. That is, every state that has the `java_options` containing these values.
  - java_options: ["-Djgroups.bundler.type=tq", "-Djgroups.bundler.use_single_sender_thread=false"]
