# JDKs utilized for testing
jdks:
  - 17.0.13-tem
  - 21.0.2-open
  - 25.ea.10-open
jdk_version: 21.0.2-open

vthreads:
  - true
  - false

# States not allowed in the permutation.
forbidden_states:
  - jdk_version: 17.0.13-tem
    use_virtual_threads: true
