- debug:
    msg: "Server Operation is {{ operation | default('DEFAULT') }}"

- name: Initializing benchmark requirements
  ansible.builtin.include_tasks: init.yml
  when: operation is undefined or operation is search("init")

- name: Upload benchmark files
  ansible.builtin.include_tasks: upload.yml
  when: operation is undefined or operation is search("upload")

- name: Starting IspnPerf
  ansible.builtin.include_tasks: start.yml
  when: operation is defined and operation is search("start")

- name: Stopping IspnPerf
  ansible.builtin.include_tasks: stop.yml
  when: operation is defined and operation is search("stop")

- name: Run all test permutations
  ansible.builtin.include_tasks: complete.yml
  vars:
    jdk_version: "{{ c.jdk_version }}"
    use_virtual_threads: "{{ c.use_virtual_threads }}"
    controller_host: "{{ groups['controller'][0] }}"
    ansible_user: "{{ hostvars[groups['controller'][0]]['ansible_user'] }}"
  loop: "{{ benchmark_configuration }}"
  loop_control:
    loop_var: c
  when: benchmark_configuration is defined and operation is defined and operation is search("run")
