- name: Show operation details
  ansible.builtin.debug:
    msg: "Server Operation is {{ operation | default('DEFAULT') }}"

- name: Initializing benchmark requirements
  ansible.builtin.include_tasks: init.yml
  when: operation is undefined or operation is search("init")

- name: Upload benchmark files
  ansible.builtin.include_tasks: upload.yml
  when: operation is undefined or operation is search("upload")

- name: Starting IspnPerf
  ansible.builtin.include_tasks: "{{ raft | ansible.builtin.ternary('start-raft.yml', 'start.yml') }}"
  when: operation is defined and operation is search("start")

- name: Stopping IspnPerf
  ansible.builtin.include_tasks: stop.yml
  when: operation is defined and operation is search("stop")

- name: Cleaning up files
  ansible.builtin.include_tasks: clean.yml
  when: operation is defined and operation is search("clean")

- name: Downloading JFR file
  ansible.builtin.include_tasks: download.yml
  when: operation is defined and operation is search('download') and file_path is defined

- name: Run all test permutations
  ansible.builtin.include_tasks: complete.yml
  vars:
    jdk_version: "{{ c.jdk_version }}"
    use_virtual_threads: "{{ c.use_virtual_threads }}"
    controller_host: "{{ groups['controller'][0] }}"
    ansible_user: "{{ hostvars[groups['controller'][0]]['ansible_user'] }}"
    benchmark_java_opts: "{{ c.java_options | join(' ') }}"
  loop: "{{ benchmark_configuration }}"
  loop_control:
    loop_var: c
  when: benchmark_configuration is defined and operation is defined and operation is search("run")
