- block:
    - name: Define JVM options
      ansible.builtin.set_fact:
        jvm_opts: "-Dorg.infinispan.threads.virtual={{ use_virtual_threads }} -Dvthreads={{ use_virtual_threads }} {{ java_opts }} {{ benchmark_java_opts }}"
        
    - name: Show JVM options
      ansible.builtin.debug:
        msg: "JVM Options: {{ jvm_opts }}"

    - name: "Running {{ script_file }}"
      ansible.builtin.shell: |
        source {{ sdkman_folder }}/bin/sdkman-init.sh
        sdk use java {{ jdk_version }}
        nohup {{ remote_folder }}/bin/{{ script_file }} \
          -control-cfg {{ control_config }} \
          -cfg {{ cache_config }} \
          -use-vthreads {{ use_virtual_threads }} \
          -threads {{ num_threads }} \
          -keys {{ num_keys }} \
          -time {{ test_duration }} \
          -warmup {{ warmup_duration }} \
          -msg-size {{ msg_size }} \
          -read-percentage {{ read_percentage }} \
          -nodes {{ groups['instances'] | length }} \
          -csv "jdk,jg,ispn,jg-vthreads,ispn-vthreads,env-props" \
          {{ batch_mode | ansible.builtin.ternary('-batch-mode true', '') }} \
          {{ nohup_mode | ansible.builtin.ternary('-nohup', '') }} &> ispn-perf.log &
      args:
        executable: /bin/bash
      environment:
        JAVA_OPTS: "{{ jvm_opts }}"
