- name: "Upload script files"
  synchronize: src="{{ bin_folder }}" dest="{{ remote_folder }}"

- name: "Upload target folder"
  synchronize: src="{{ target_folder }}" dest="{{ remote_folder }}"

- name: "Upload env file"
  synchronize: src="env" dest="{{ remote_folder }}"

- name: Create hosts file
  template:
    src: hosts.txt.j2
    dest: "{{ remote_folder }}/target/classes/hosts.txt"
