- name: Verify if operation permitted
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Verify operation
      ansible.builtin.fail:
        msg: "Operation '{{ operation }}' is not allowed in this playbook!"
      when: operation is defined and (operation is search("start") or operation is search("stop"))

- name: "Run operation {{ operation | default('') }}"
  hosts: "instances"
  roles: [benchmark]
