- name: Start controller node
  hosts: controller
  roles: [benchmark]
  vars:
    operation: start

- name: Wait until controller started
  hosts: controller
  tasks:
    - name: Wait until coordinator started
      ansible.builtin.wait_for:
        path: '/home/{{ ansible_user }}/ispn-perf.log'
        search_regex: Node completed start setup
        timeout: 20

- name: Starte remaining nodes
  hosts: "instances:!controller"
  roles: [benchmark]
  vars:
    operation: start

- name: Run benchmark steps.
  hosts: controller
  tasks:
    - name: Time we started waiting for the test to complete
      ansible.builtin.debug:
        msg: "Starting to listen: {{ now() }}"

    - name: Wait until test finished
      ansible.builtin.wait_for:
        path: '/home/{{ ansible_user }}/ispn-perf.log'
        search_regex: Test execution completed

    - name: Download results.txt from controller
      ansible.builtin.fetch:
        src: '/home/{{ ansible_user }}/results.txt'
        dest: results.txt
        flat: true

    - name: Download results.csv from controller
      ansible.builtin.fetch:
        src: '/home/{{ ansible_user }}/results.csv'
        dest: results.csv
        flat: true
