{
 "title": "Benchmark",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "vendor_cache_container_health_number_of_cpus"
    }
   }
  ]
 },
 "panels": [
  { "title": "$instance stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "$instance - CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad{instance=~\"$instance\"}",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "$instance - Read Response Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (idelta(requests_seconds_bucket{instance=~\"$instance\", operation=\"GET\"} [2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$instance - Write Response Time",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (le) (idelta(requests_seconds_bucket{instance=~\"$instance\", operation=\"PUT\"} [2m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "$instance - 99 quantile millis",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (irate(requests_seconds_bucket{instance=~\"$instance\", operation=\"GET\"}[2m])))",
     "legendFormat": "GET"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (irate(requests_seconds_bucket{instance=~\"$instance\", operation=\"PUT\"}[2m])))",
     "legendFormat": "PUT"
    }
   ]
  }
 ]
}